version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: flashsale_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashsale
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: flashsale_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flashsale_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  pgadmin:
    image: dpage/pgadmin4
    container_name: flashsale_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vinhtungnguyen2005@gmail.com
      PGADMIN_DEFAULT_PASSWORD: vtung2005
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: